dist: trusty
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - /^\d.\d+$/

matrix:
  fast_finish: true
  include:
# 7.3
    - name: '[PHP 7.3] Unit tests'
      php: 7.3
      env: TEST_CONFIG="phpunit.xml"
# 7.2
    - NAME: '[PHP 7.2] Unit tests'
      php: 7.2
      env: TEST_CONFIG="phpunit.xml"
# CS check
    - name: 'Code Style Check'
      php: 7.3
      env: CHECK_CS=true

before_install:
  # Disable xdebug to speed things up as we don't currently generate coverage on travis
  - phpenv config-rm xdebug.ini
  # Add custom php.ini configuration for test matrix
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "default_charset=UTF-8" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - travis_retry composer install --no-progress --no-interaction --prefer-dist --no-suggest

script:
  - if [ "${TEST_CONFIG}" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE ./vendor/bin/phpunit -c $TEST_CONFIG ; fi
  - if [ "${CHECK_CS}" = "true" ] ; then ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi
